name: Continuous Integration

on:
  [pull_request, push]

jobs:
  build-js:
    name: "Build JS"
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@master
    - uses: c-hive/gha-yarn-cache@v1

    - name: Install node modules
      run: |
        yarn install
        
    - name: Run test
      run: |
        yarn test
  build-ios:
    name: "Build iOS Sample App"
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@master
    - uses: c-hive/gha-yarn-cache@v1

    - name: Install Node Modules
      run: npm install; yarn install

    - name: Install Node Modules, Sample App
      working-directory: sample
      run: npm install; yarn install

    - name: Install Pods, Sample App
      working-directory: sample/ios
      run: pod install

    - name: XCode build
      working-directory: sample/ios
      run: xcodebuild -allowProvisioningUpdates -workspace sampleApp.xcworkspace -scheme sampleApp -destination 'platform=iOS Simulator,name=iPhone 11,OS=latest'

  android-unit-tests:
    name: "Run Android Unit Tests"
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Run Android Unit Tests
        run: echo "pwd"; pwd; echo "ls:"; ls; cd android; ./gradlew test